server {
    listen 80;
    server_name _;

    # 主站静态文件
    root /usr/share/nginx/templates/web;
    index index.html;

    # 网站API接口
    location ^~ /api/ {
        proxy_pass http://backend:10057;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    # sse-markdown 静态 Demo
    location = /io/sse-markdown {
        return 308 $scheme://$http_host/io/sse-markdown/;
    }

    location ^~ /io/sse-markdown/ {
        alias /usr/share/nginx/templates/sse-markdown/;
        try_files $uri $uri/ /io/sse-markdown/index.html;
    }

    # git-folder-dashboard 静态 Demo
    location = /io/git-folder-dashboard {
        return 308 $scheme://$http_host/io/git-folder-dashboard/;
    }

    location ^~ /io/git-folder-dashboard/ {
        alias /usr/share/nginx/templates/git-folder-dashboard/;
        try_files $uri $uri/ /io/git-folder-dashboard/index.html;
    }

    # 主站 SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
