server {
    listen 80;
    server_name _;

    # 主站静态文件
    root /usr/share/nginx/www/web;
    index index.html;

    # 网站API接口
    location ^~ /api/ {
        proxy_pass http://backend:10057;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    # sse-markdown 静态 Demo
    location = /io/sse-markdown {
        return 308 $scheme://$http_host/io/sse-markdown/;
    }

    location ^~ /io/sse-markdown/ {
        alias /usr/share/nginx/www/sse-markdown/;
        try_files $uri $uri/ /io/sse-markdown/index.html;
    }

    # git-folder-dashboard 静态 Demo
    location = /io/git-folder-dashboard {
        return 308 $scheme://$http_host/io/git-folder-dashboard/;
    }

    location ^~ /io/git-folder-dashboard/ {
        alias /usr/share/nginx/www/git-folder-dashboard/;
        try_files $uri $uri/ /io/git-folder-dashboard/index.html;
    }
    
    
    # html-edge-tts-video 静态 Demo
    location = /io/html2video {
        return 308 $scheme://$http_host/io/html2video/;
    }

    location ^~ /io/html2video/ {
        alias /usr/share/nginx/www/html-edge-tts-video/;
        try_files $uri $uri/ /io/html2video/index.html;
    }
    
    
    # ==============================
    # ai-api-hub DashScope 反代
    # 只允许 /io/llm 下使用
    # ==============================
    location ^~ /io/llm/ai-api-hub-dashscope-proxy/ {
        proxy_pass https://dashscope.aliyuncs.com/;

        proxy_http_version 1.1;
        proxy_ssl_server_name on;

        proxy_set_header Host dashscope.aliyuncs.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 透传 Authorization、X-DashScope-Async 等请求头
        proxy_pass_request_headers on;

        # 如果有流式输出，建议加上这些
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # ai-api-hub 静态 Demo
    location = /io/llm {
        return 308 $scheme://$http_host/io/llm/;
    }

    location ^~ /io/llm/ {
        alias /usr/share/nginx/www/ai-api-hub/;
        try_files $uri $uri/ /io/llm/index.html;
    }

    # 主站 SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
